version: '3.8'
services:
#  socat:
#    image: alpine/socat
#    command: "pty,rawer exec:'/bin/cat'"

  counter:
    build:
      context: ../app
      dockerfile: Dockerfile
    restart: unless-stopped
#    devices:
#      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ./settings.py:/code/app/settings.py

  counter-nginx:
#    image: nginx:1.25.1
    image: nginx:1.25
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - counter

networks:
  network-example:
    external: true
