name: OwenPulseCounterAPI workflow
on:
  push:
    branches:
      - "master"

jobs:
  build_and_push_backend_to_docker_hub:
    if: ${{ github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: app
          push: true
          tags: aleksup/owen_counter_api:latest

  send_message:
    if: ${{ always() }}
    needs: [ build_and_push_backend_to_docker_hub ]
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.workflow }}
            Actor: ${{ github.actor }}
            Branch: ${{ github.ref_name }}
            Results:
              building and pushing back: ${{ needs.build_and_push_backend_to_docker_hub.result }}
